/**
 * YouTube 字幕抓取的数据契约。
 * 放在 shared/ 而非 extension/content/，避免 shared/messages.ts 反向依赖 extension/。
 */

import type { SubtitleCue } from '@core/types';

export const YOUTUBE_TRANSCRIPT_CACHE_TTL_MS = 5 * 60 * 1000;

export type YouTubeTranscriptErrorCode =
  | 'NO_VIDEO_ID'
  | 'CONTENT_SCRIPT_UNAVAILABLE'
  | 'NETWORK_ERROR'
  | 'INVALID_VIDEO_ID'
  | 'NO_VIDEO_ID_IN_RESPONSE'
  | 'NO_PLAYABILITY'
  | 'NO_CAPTION_TRACKS'
  | 'UNPLAYABLE'
  | 'PLAYER_UNPLAYABLE'
  | 'INNERTUBE_BAD_STATUS'
  | 'TIMEDTEXT_BAD_STATUS'
  | 'TIMEDTEXT_EMPTY_BODY'
  | 'NO_TRACK_CANDIDATE'
  | 'XML_PARSER_ERROR'
  | 'XML_UNRECOGNIZED_FORMAT'
  | 'NO_CUES';

export interface YouTubeTranscriptError {
  readonly code: YouTubeTranscriptErrorCode;
  readonly message: string;
  /** HTTP 状态；网络层错误或 DOM 面板解析错误时为 undefined。 */
  readonly status?: number;
  /** 用于耗时明细的失败阶段标签。 */
  readonly stage:
    | 'extract_video_id'
    | 'dom_panel'
    | 'parse_dom'
    | 'innertube'
    | 'pick_track'
    | 'timedtext'
    | 'parse_xml'
    | 'cache';
}

export interface YouTubeTranscriptAttempt {
  readonly stage: string;
  readonly language?: string;
  readonly source?: 'official' | 'asr';
  readonly status?: number;
  readonly cueCount?: number;
  readonly durationMs: number;
  readonly error?: string;
}

export interface YouTubePageCaptionTrackName {
  readonly simpleText?: string;
  readonly runs?: readonly { readonly text?: string }[];
}

/**
 * 从 YouTube 当前播放器对象读出的字幕轨。
 *
 * 这份类型放在 shared 层，是因为 background 需要先在 MAIN world 读取
 * `#movie_player.getPlayerResponse()`，再把结果通过消息交给 content script 拉取
 * timedtext。不要在 shared/messages 里反向依赖 extension/content 的内部类型。
 */
export interface YouTubePageCaptionTrack {
  readonly baseUrl: string;
  readonly languageCode?: string;
  readonly kind?: string;
  readonly name?: YouTubePageCaptionTrackName | null;
  readonly vssId?: string | null;
}

export interface YouTubeTranscriptResult {
  readonly videoId: string;
  readonly metadata: {
    readonly title: string | null;
    readonly author: string | null;
    readonly lengthSeconds: number | null;
  };
  readonly track: {
    readonly language: string;
    readonly label: string;
    readonly source: 'official' | 'asr';
    readonly isAutoGenerated: boolean;
  };
  readonly availableTrackCount: number;
  readonly cues: readonly SubtitleCue[];
  readonly cached: boolean;
  readonly timings: readonly YouTubeTranscriptAttempt[];
}
