import { describe, expect, it, vi } from 'vitest';
import {
  createChromeContentScriptBridge,
  createContentScriptBridge,
  readYouTubePlayerCaptionTracksInMainWorld,
} from '@extension/background/services/content-script-bridge';
import type { ContentScriptBridgeDeps } from '@extension/background/services/content-script-bridge';
import type { ExtensionResponse } from '@shared/messages';
import type {
  YouTubeTranscriptError,
  YouTubeTranscriptResult,
} from '@shared/youtube-transcript';
import type { PlaybackState } from '@shared/playback-state';

function makeResult(videoId = 'dQw4w9WgXcQ'): YouTubeTranscriptResult {
  return {
    videoId,
    metadata: {
      title: 'never gonna',
      author: 'rick astley',
      lengthSeconds: 213,
    },
    track: { language: 'en', label: 'English', source: 'official', isAutoGenerated: false },
    availableTrackCount: 1,
    cues: [{ start: 0, end: 1, text: 'hello' }],
    cached: false,
    timings: [{ stage: 'dom_panel', durationMs: 100 }],
  };
}

function makePlayback(): PlaybackState {
  return { currentTime: 60, duration: 600, paused: false, updatedAt: 100 };
}

function makeError(overrides: Partial<YouTubeTranscriptError> = {}): YouTubeTranscriptError {
  return {
    code: 'NETWORK_ERROR',
    message: 'test',
    stage: 'dom_panel',
    ...overrides,
  };
}

interface FakeClock {
  now: ReturnType<typeof vi.fn>;
  sleep: ReturnType<typeof vi.fn>;
  /** 记录 sleep 调用顺序（替代真实 elapsed time 断言）。 */
  sleepCalls: number[];
}

function makeFakeClock(start = 0): FakeClock {
  const sleepCalls: number[] = [];
  let fakeNow = start;
  const sleep = vi.fn(async (ms: number) => {
    sleepCalls.push(ms);
    fakeNow += ms;
  });
  const now = vi.fn(() => fakeNow);
  return { now, sleep, sleepCalls };
}

function makeDeps(overrides: Partial<ContentScriptBridgeDeps> = {}): ContentScriptBridgeDeps {
  return {
    sendMessage: vi.fn(),
    injectContentScript: vi.fn().mockResolvedValue(true),
    sleep: vi.fn().mockResolvedValue(undefined),
    now: () => 0,
    createErrorResponse: (code, message) => ({ ok: false, error: { code, message } }),
    ...overrides,
  };
}

describe('createContentScriptBridge', () => {
  describe('sendMessageWithRecovery (内部 — 通过 fetchYouTubeTranscript / readPlaybackState / seekVideo 验证)', () => {
    it('first sendMessage 成功 → 不调 injectContentScript', async () => {
      const injectContentScript = vi.fn().mockResolvedValue(true);
      const deps = makeDeps({
        sendMessage: vi.fn().mockResolvedValue({ ok: true, response: { ok: 'x' } }),
        injectContentScript,
      });
      const bridge = createContentScriptBridge(deps);
      await bridge.fetchYouTubeTranscript(1, { videoId: 'v' });
      expect(injectContentScript).not.toHaveBeenCalled();
    });

    it('first sendMessage 拿到非 CONTENT_SCRIPT_UNAVAILABLE 错误 → 不调 inject，直接返回错误', async () => {
      const injectContentScript = vi.fn().mockResolvedValue(true);
      const deps = makeDeps({
        sendMessage: vi.fn().mockResolvedValue({
          ok: false,
          code: 'NETWORK_ERROR',
          message: 'tab not found',
        }),
        injectContentScript,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.fetchYouTubeTranscript(1, { videoId: 'v' });
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe('NETWORK_ERROR');
      }
      expect(injectContentScript).not.toHaveBeenCalled();
    });

    it('first sendMessage CONTENT_SCRIPT_UNAVAILABLE + inject 失败 → 返回 CONTENT_SCRIPT_UNAVAILABLE', async () => {
      const deps = makeDeps({
        sendMessage: vi.fn().mockResolvedValue({
          ok: false,
          code: 'CONTENT_SCRIPT_UNAVAILABLE',
          message: 'recv end',
        }),
        injectContentScript: vi.fn().mockResolvedValue(false),
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.fetchYouTubeTranscript(1, { videoId: 'v' });
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe('CONTENT_SCRIPT_UNAVAILABLE');
      }
    });
  });

  describe('fetchYouTubeTranscript', () => {
    it('first 拿到 YOUTUBE_TRANSCRIPT_FAILED（非 CONTENT_SCRIPT_UNAVAILABLE）→ 立即返回错误', async () => {
      const injectContentScript = vi.fn();
      const deps = makeDeps({
        sendMessage: vi.fn().mockResolvedValue({
          ok: true,
          response: {
            type: 'YOUTUBE_TRANSCRIPT_FAILED',
            error: makeError({ code: 'INNERTUBE_BAD_STATUS', status: 500 }),
          },
        }),
        injectContentScript,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.fetchYouTubeTranscript(1, { videoId: 'v' });
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe('INNERTUBE_BAD_STATUS');
      }
      // 真实业务错误 → 不注入、不轮询
      expect(injectContentScript).not.toHaveBeenCalled();
    });

    it('会把 MAIN world 读取到的当前播放器字幕轨随请求传给 content script', async () => {
      const pageCaptionTracks = [
        {
          baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en',
          languageCode: 'en',
          name: { simpleText: 'English' },
        },
      ];
      const sendMessage = vi.fn().mockResolvedValue({
        ok: true,
        response: {
          type: 'YOUTUBE_TRANSCRIPT',
          payload: { result: makeResult(), attempts: [{ stage: 'caption_tracks', durationMs: 5 }] },
        },
      });
      const readYouTubePlayerCaptionTracks = vi.fn().mockResolvedValue(pageCaptionTracks);
      const deps = makeDeps({
        sendMessage,
        readYouTubePlayerCaptionTracks,
      });
      const bridge = createContentScriptBridge(deps);

      const result = await bridge.fetchYouTubeTranscript(7, { videoId: 'dQw4w9WgXcQ' });

      expect(result.ok).toBe(true);
      expect(readYouTubePlayerCaptionTracks).toHaveBeenCalledWith(7, 'dQw4w9WgXcQ');
      expect(sendMessage.mock.calls[0]?.[1]).toMatchObject({
        type: 'FETCH_YOUTUBE_TRANSCRIPT',
        payload: {
          videoId: 'dQw4w9WgXcQ',
          pageCaptionTracks,
        },
      });
    });

    it('MAIN world 字幕轨读取失败时不阻塞原有 content script 请求', async () => {
      const sendMessage = vi.fn().mockResolvedValue({
        ok: true,
        response: {
          type: 'YOUTUBE_TRANSCRIPT',
          payload: { result: makeResult(), attempts: [{ stage: 'dom_panel', durationMs: 100 }] },
        },
      });
      const deps = makeDeps({
        sendMessage,
        readYouTubePlayerCaptionTracks: vi.fn().mockRejectedValue(new Error('no access')),
      });
      const bridge = createContentScriptBridge(deps);

      const result = await bridge.fetchYouTubeTranscript(7, { videoId: 'dQw4w9WgXcQ' });

      expect(result.ok).toBe(true);
      expect(sendMessage.mock.calls[0]?.[1]).toEqual({
        type: 'FETCH_YOUTUBE_TRANSCRIPT',
        payload: { videoId: 'dQw4w9WgXcQ' },
      });
    });

    it('第一次 CONTENT_SCRIPT_UNAVAILABLE → 注入 + 轮询 listener 路由 + 拿到 ok', async () => {
      const clk = makeFakeClock();
      let callCount = 0;
      const deps = makeDeps({
        sendMessage: vi.fn().mockImplementation(async () => {
          callCount += 1;
          if (callCount === 1) {
            return { ok: false, code: 'CONTENT_SCRIPT_UNAVAILABLE', message: 'recv end' };
          }
          // 第 2 次及之后都返回成功
          return {
            ok: true,
            response: {
              type: 'YOUTUBE_TRANSCRIPT',
              payload: { result: makeResult(), attempts: [{ stage: 'dom_panel', durationMs: 100 }] },
            },
          };
        }),
        injectContentScript: vi.fn().mockResolvedValue(true),
        sleep: clk.sleep,
        now: clk.now,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.fetchYouTubeTranscript(1, { videoId: 'v' });
      expect(result.ok).toBe(true);
      // 第一次失败 → 注入后固定 sleep 200ms → 第二次走 sendMessageWithRecovery 成功
      expect(clk.sleepCalls[0]).toBe(200);
    });

    it('轮询期间拿到 YOUTUBE_TRANSCRIPT_FAILED → 立即返回，不等剩余 backoff', async () => {
      const clk = makeFakeClock();
      let callCount = 0;
      const deps = makeDeps({
        sendMessage: vi.fn().mockImplementation(async () => {
          callCount += 1;
          if (callCount === 1) {
            return { ok: false, code: 'CONTENT_SCRIPT_UNAVAILABLE', message: 'recv end' };
          }
          if (callCount === 2) {
            // 第二次走 sendMessageWithRecovery，注入后 sleep 200ms；本身返回成功但
            // payload 是 FAILED → waitForContentScriptListener 立即识别并 return
            return {
              ok: true,
              response: {
                type: 'YOUTUBE_TRANSCRIPT_FAILED',
                error: makeError({ code: 'INNERTUBE_BAD_STATUS' }),
              },
            };
          }
          return { ok: true, response: { type: 'UNKNOWN' } };
        }),
        injectContentScript: vi.fn().mockResolvedValue(true),
        sleep: clk.sleep,
        now: clk.now,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.fetchYouTubeTranscript(1, { videoId: 'v' });
      expect(result.ok).toBe(false);
      // 真实业务错误立即返回 → 没有进入 backoff 轮询
      expect(clk.sleepCalls).toEqual([200]);
    });

    it('listener 轮询期间 sendMessage 持续失败 → 累计到 timeoutMs 后返回 CONTENT_SCRIPT_UNAVAILABLE', async () => {
      // 用 fake clock 模拟累计耗时；3_000ms timeout + 5 次 backoff 总和 3_000
      const clk = makeFakeClock(0);
      const deps = makeDeps({
        sendMessage: vi.fn().mockResolvedValue({
          ok: false,
          code: 'CONTENT_SCRIPT_UNAVAILABLE',
          message: 'recv end',
        }),
        injectContentScript: vi.fn().mockResolvedValue(true),
        sleep: clk.sleep,
        now: clk.now,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.fetchYouTubeTranscript(1, { videoId: 'v' });
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe('CONTENT_SCRIPT_UNAVAILABLE');
        expect(result.error.message).toMatch(/注入后 3000ms/);
      }
      // 轮询 backoff [200, 300, 500, 800, 1200] 累加 200/500/1000/1800/3000
      // 累加到 3000 时跳出
      expect(clk.sleepCalls).toEqual([200, 300, 500, 800, 1200]);
    });

    // QA1 必修 A1：listener 已可路由但返回未知响应时 → 立即返回 NETWORK_ERROR
    // （旧实现行为：不继续轮询，不改写成 CONTENT_SCRIPT_UNAVAILABLE）
    it('轮询期间拿到未知响应 → 立即返回 NETWORK_ERROR（不继续轮询）', async () => {
      const clk = makeFakeClock();
      let callCount = 0;
      const deps = makeDeps({
        sendMessage: vi.fn().mockImplementation(async () => {
          callCount += 1;
          if (callCount === 1) {
            return { ok: false, code: 'CONTENT_SCRIPT_UNAVAILABLE', message: 'recv end' };
          }
          // 第 2 次及之后：注入后 listener 已可路由但 type 不识别
          return { ok: true, response: { ok: true, type: 'UNKNOWN' } };
        }),
        injectContentScript: vi.fn().mockResolvedValue(true),
        sleep: clk.sleep,
        now: clk.now,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.fetchYouTubeTranscript(1, { videoId: 'v' });
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe('NETWORK_ERROR');
        expect(result.error.message).toBe('content script 返回了未识别的响应');
        expect(result.error.stage).toBe('dom_panel');
      }
      // 只发生一次 200ms listener backoff；不继续轮询剩余 300/500/800/1200
      expect(clk.sleepCalls).toEqual([200]);
    });

    // QA1 必修 A3：YOUTUBE_TRANSCRIPT_FAILED 但 error 缺失 → 沿用原文案
    it('轮询期间 YOUTUBE_TRANSCRIPT_FAILED 缺 error → 用旧文案 `content script 返回了未知错误`', async () => {
      const clk = makeFakeClock();
      let callCount = 0;
      const deps = makeDeps({
        sendMessage: vi.fn().mockImplementation(async () => {
          callCount += 1;
          if (callCount === 1) {
            return { ok: false, code: 'CONTENT_SCRIPT_UNAVAILABLE', message: 'recv end' };
          }
          return {
            ok: true,
            response: { ok: false, type: 'YOUTUBE_TRANSCRIPT_FAILED' /* 缺 error */ },
          };
        }),
        injectContentScript: vi.fn().mockResolvedValue(true),
        sleep: clk.sleep,
        now: clk.now,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.fetchYouTubeTranscript(1, { videoId: 'v' });
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe('NETWORK_ERROR');
        expect(result.error.message).toBe('content script 返回了未知错误');
      }
      expect(clk.sleepCalls).toEqual([200]);
    });
  });

  describe('readYouTubePlayerCaptionTracksInMainWorld', () => {
    it('从当前 #movie_player.getPlayerResponse() 读取字幕轨，并过滤旧视频轨道', async () => {
      const moviePlayer = document.createElement('div') as HTMLDivElement & {
        getPlayerResponse: () => unknown;
      };
      moviePlayer.id = 'movie_player';
      moviePlayer.getPlayerResponse = () => ({
        videoDetails: { videoId: 'dQw4w9WgXcQ' },
        captions: {
          playerCaptionsTracklistRenderer: {
            captionTracks: [
              {
                baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en',
                languageCode: 'en',
                name: { simpleText: 'English' },
              },
              {
                baseUrl: 'https://www.youtube.com/api/timedtext?v=OLD_VIDEO_1&lang=en',
                languageCode: 'en',
                name: { simpleText: 'Old English' },
              },
            ],
          },
        },
      });
      document.body.append(moviePlayer);

      const tracks = await readYouTubePlayerCaptionTracksInMainWorld('dQw4w9WgXcQ');

      expect(tracks).toEqual([
        {
          baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en',
          languageCode: 'en',
          name: { simpleText: 'English' },
          vssId: null,
        },
      ]);
      moviePlayer.remove();
    });

    it('播放器响应 videoId 不匹配时拒绝使用，避免 YouTube SPA 旧数据污染', async () => {
      const moviePlayer = document.createElement('div') as HTMLDivElement & {
        getPlayerResponse: () => unknown;
      };
      moviePlayer.id = 'movie_player';
      moviePlayer.getPlayerResponse = () => ({
        videoDetails: { videoId: 'OLD_VIDEO_1' },
        captions: {
          playerCaptionsTracklistRenderer: {
            captionTracks: [
              {
                baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en',
                languageCode: 'en',
              },
            ],
          },
        },
      });
      document.body.append(moviePlayer);

      await expect(readYouTubePlayerCaptionTracksInMainWorld('dQw4w9WgXcQ')).resolves.toEqual([]);
      moviePlayer.remove();
    });

    it('优先返回 performance 里播放器生成的带 pot timedtext URL', async () => {
      const originalGetEntriesByType = performance.getEntriesByType;
      Object.defineProperty(performance, 'getEntriesByType', {
        configurable: true,
        value: vi.fn().mockReturnValue([
          {
            name: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en-US&potc=1&pot=abc&fmt=json3',
          },
        ]),
      });
      const moviePlayer = document.createElement('div') as HTMLDivElement & {
        getPlayerResponse: () => unknown;
      };
      moviePlayer.id = 'movie_player';
      moviePlayer.getPlayerResponse = () => ({
        videoDetails: { videoId: 'dQw4w9WgXcQ' },
        captions: {
          playerCaptionsTracklistRenderer: {
            captionTracks: [
              {
                baseUrl:
                  'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en-US&exp=xpe',
                languageCode: 'en-US',
                name: { simpleText: 'English' },
              },
            ],
          },
        },
      });
      document.body.append(moviePlayer);

      const tracks = await readYouTubePlayerCaptionTracksInMainWorld('dQw4w9WgXcQ');

      expect(tracks).toEqual([
        {
          baseUrl:
            'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en-US&potc=1&pot=abc&fmt=json3',
          languageCode: 'en-US',
          kind: 'official',
          name: { simpleText: 'English' },
          vssId: null,
        },
      ]);
      moviePlayer.remove();
      Object.defineProperty(performance, 'getEntriesByType', {
        configurable: true,
        value: originalGetEntriesByType,
      });
    });
  });

  describe('readPlaybackState', () => {
    it('first sendMessage 失败 → 返回 null，不重试', async () => {
      const clk = makeFakeClock();
      const deps = makeDeps({
        sendMessage: vi.fn().mockResolvedValue({
          ok: false,
          code: 'NETWORK_ERROR',
          message: 'tab not found',
        }),
        sleep: clk.sleep,
        now: clk.now,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.readPlaybackState(1);
      expect(result).toBeNull();
      // NETWORK_ERROR → 不轮询
      expect(clk.sleepCalls).toEqual([]);
    });

    it('first 拿到 PLAYBACK_STATE + payload → 返回 payload', async () => {
      const playback = makePlayback();
      const deps = makeDeps({
        sendMessage: vi.fn().mockResolvedValue({
          ok: true,
          response: { ok: true, type: 'PLAYBACK_STATE', payload: playback } as ExtensionResponse,
        }),
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.readPlaybackState(1);
      expect(result).toBe(playback);
    });

    it('first 拿到 PLAYBACK_STATE + payload=null → 短间隔重试 [100, 250, 500, 1000]，第二次成功', async () => {
      const clk = makeFakeClock();
      const playback = makePlayback();
      let callCount = 0;
      const deps = makeDeps({
        sendMessage: vi.fn().mockImplementation(async () => {
          callCount += 1;
          if (callCount === 1) {
            return {
              ok: true,
              response: { ok: true, type: 'PLAYBACK_STATE', payload: null } as ExtensionResponse,
            };
          }
          return {
            ok: true,
            response: { ok: true, type: 'PLAYBACK_STATE', payload: playback } as ExtensionResponse,
          };
        }),
        sleep: clk.sleep,
        now: clk.now,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.readPlaybackState(1);
      expect(result).toBe(playback);
      // 第一次 payload=null → 短间隔 100ms 后重试 → 第二次成功
      expect(clk.sleepCalls).toEqual([100]);
    });

    it('所有重试都拿到 payload=null → 最终返回 null', async () => {
      const clk = makeFakeClock();
      const deps = makeDeps({
        sendMessage: vi.fn().mockResolvedValue({
          ok: true,
          response: { ok: true, type: 'PLAYBACK_STATE', payload: null } as ExtensionResponse,
        }),
        sleep: clk.sleep,
        now: clk.now,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.readPlaybackState(1);
      expect(result).toBeNull();
      // 重试间隔 [100, 250, 500, 1000] 都触发
      expect(clk.sleepCalls).toEqual([100, 250, 500, 1000]);
    });

    it('重试期间 sendMessage 失败 → 立即返回 null', async () => {
      const clk = makeFakeClock();
      let callCount = 0;
      const deps = makeDeps({
        sendMessage: vi.fn().mockImplementation(async () => {
          callCount += 1;
          if (callCount === 1) {
            return {
              ok: true,
              response: { ok: true, type: 'PLAYBACK_STATE', payload: null } as ExtensionResponse,
            };
          }
          return { ok: false, code: 'NETWORK_ERROR', message: 'lost' };
        }),
        sleep: clk.sleep,
        now: clk.now,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.readPlaybackState(1);
      expect(result).toBeNull();
      // 第一次 payload=null → sleep 100ms → 第二次 sendMessage 失败 → 立即返回
      expect(clk.sleepCalls).toEqual([100]);
    });

    // QA1 必修 C：显式覆盖 sendMessageWithRecovery 内部"first C_S_U + inject + 200ms + retry 成功"
    // 路径。readPlaybackState 第一次就调 sendMessageWithRecovery（不是 fetchYouTubeTranscript
    // 的"先 sendMessage 单次再注入再 polling"路径），所以这个测例真正走过 sendMessageWithRecovery。
    it('sendMessageWithRecovery 路径：first C_S_U + inject 成功 + 200ms + retry 成功 → 返回 playback', async () => {
      const clk = makeFakeClock();
      const playback = makePlayback();
      let callCount = 0;
      const injectContentScript = vi.fn().mockResolvedValue(true);
      const deps = makeDeps({
        sendMessage: vi.fn().mockImplementation(async () => {
          callCount += 1;
          if (callCount === 1) {
            return { ok: false, code: 'CONTENT_SCRIPT_UNAVAILABLE', message: 'recv end' };
          }
          return {
            ok: true,
            response: {
              ok: true,
              type: 'PLAYBACK_STATE',
              payload: playback,
            } as ExtensionResponse,
          };
        }),
        injectContentScript,
        sleep: clk.sleep,
        now: clk.now,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.readPlaybackState(1);
      expect(result).toBe(playback);
      // 1) 第一次 sendMessage 失败 → 注入（只 1 次）→ sleep 200ms（injectBackoff）
      // 2) 第二次 sendMessage 成功 → 立即返回 payload
      expect(injectContentScript).toHaveBeenCalledTimes(1);
      expect(clk.sleepCalls).toEqual([200]);
    });
  });

  describe('seekVideo', () => {
    const SEEK_REQUEST = {
      type: 'SEEK_ACTIVE_VIDEO' as const,
      payload: { seconds: 120 },
    };

    it('first sendMessage 成功 + found:true → 返回 DONE', async () => {
      const deps = makeDeps({
        sendMessage: vi.fn().mockResolvedValue({
          ok: true,
          response: { ok: true, type: 'DONE', found: true },
        }),
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.seekVideo(1, SEEK_REQUEST);
      expect(result).toEqual({ ok: true, type: 'DONE' });
    });

    it('first sendMessage 注入失败 → 返回 CONTENT_SCRIPT_UNAVAILABLE（**不**进入短间隔重试）', async () => {
      const clk = makeFakeClock();
      const createErrorResponse = vi.fn(
        (code: string, message: string): ExtensionResponse => ({
          ok: false,
          error: { code, message },
        }),
      );
      const deps = makeDeps({
        sendMessage: vi.fn().mockResolvedValue({
          ok: false,
          code: 'CONTENT_SCRIPT_UNAVAILABLE',
          message: 'recv end',
        }),
        injectContentScript: vi.fn().mockResolvedValue(false),
        createErrorResponse,
        sleep: clk.sleep,
        now: clk.now,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.seekVideo(1, SEEK_REQUEST);
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe('CONTENT_SCRIPT_UNAVAILABLE');
        expect(result.error.message).toMatch(/刷新/);
      }
      expect(createErrorResponse).toHaveBeenCalled();
      expect(clk.sleepCalls).toEqual([]);
    });

    it('first found:false → 短间隔重试 [200, 500, 1000, 1500]，第二次 found:true → DONE', async () => {
      const clk = makeFakeClock();
      let callCount = 0;
      const deps = makeDeps({
        sendMessage: vi.fn().mockImplementation(async () => {
          callCount += 1;
          if (callCount === 1) {
            return { ok: true, response: { ok: true, type: 'DONE', found: false } };
          }
          return { ok: true, response: { ok: true, type: 'DONE', found: true } };
        }),
        sleep: clk.sleep,
        now: clk.now,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.seekVideo(1, SEEK_REQUEST);
      expect(result).toEqual({ ok: true, type: 'DONE' });
      // 第一次 found:false → sleep 200ms → 第二次 found:true
      expect(clk.sleepCalls).toEqual([200]);
    });

    it('所有重试 found:false → 返回 VIDEO_ELEMENT_NOT_FOUND', async () => {
      const clk = makeFakeClock();
      const deps = makeDeps({
        sendMessage: vi.fn().mockResolvedValue({
          ok: true,
          response: { ok: true, type: 'DONE', found: false },
        }),
        sleep: clk.sleep,
        now: clk.now,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.seekVideo(1, SEEK_REQUEST);
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe('VIDEO_ELEMENT_NOT_FOUND');
        // 中文文案带"视频"或"video"
        expect(result.error.message).toMatch(/视频|video/i);
      }
      // 重试间隔 [200, 500, 1000, 1500] 都触发
      expect(clk.sleepCalls).toEqual([200, 500, 1000, 1500]);
    });

    it('重试期间 sendMessage 失败 → 立即返回错误响应', async () => {
      const clk = makeFakeClock();
      let callCount = 0;
      const deps = makeDeps({
        sendMessage: vi.fn().mockImplementation(async () => {
          callCount += 1;
          if (callCount === 1) {
            return { ok: true, response: { ok: true, type: 'DONE', found: false } };
          }
          return { ok: false, code: 'NETWORK_ERROR', message: 'lost' };
        }),
        sleep: clk.sleep,
        now: clk.now,
      });
      const bridge = createContentScriptBridge(deps);
      const result = await bridge.seekVideo(1, SEEK_REQUEST);
      expect(result.ok).toBe(false);
      // 第一次 found:false → sleep 200ms → 第二次 sendMessage 失败 → 立即错误
      expect(clk.sleepCalls).toEqual([200]);
    });
  });

  // QA1 必修 A2：Chrome adapter 按 request 类型分流同步 throw 错误码
  // （旧实现：FETCH_YOUTUBE_TRANSCRIPT → CONTENT_SCRIPT_UNAVAILABLE；其它 → NETWORK_ERROR）
  describe('createChromeContentScriptBridge.sendMessage (同步 throw 分流)', () => {
    /** 在隔离 globalThis 上模拟 chrome.tabs.sendMessage 同步抛错；返回 1 次调用的结果。 */
    function setupChromeThrow(message: string): {
      bridge: ReturnType<typeof createChromeContentScriptBridge>;
      restore: () => void;
    } {
      const originalChrome = (globalThis as { chrome?: unknown }).chrome;
      (globalThis as { chrome: { tabs: { sendMessage: (tabId: number, msg: unknown) => void } } }).chrome = {
        tabs: {
          sendMessage: (_tabId: number, _msg: unknown) => {
            throw new Error(message);
          },
        },
      };
      const bridge = createChromeContentScriptBridge({
        createErrorResponse: (code: string, msg: string) => ({
          ok: false,
          error: { code, message: msg },
        }),
        logWarn: () => undefined,
      });
      return {
        bridge,
        restore: () => {
          if (originalChrome === undefined) {
            delete (globalThis as { chrome?: unknown }).chrome;
          } else {
            (globalThis as { chrome: unknown }).chrome = originalChrome;
          }
        },
      };
    }

    it('FETCH_YOUTUBE_TRANSCRIPT 同步 throw → CONTENT_SCRIPT_UNAVAILABLE', async () => {
      const { bridge, restore } = setupChromeThrow('Could not establish connection.');
      try {
        const result = await bridge.fetchYouTubeTranscript(1, { videoId: 'v' });
        expect(result.ok).toBe(false);
        if (!result.ok) expect(result.error.code).toBe('CONTENT_SCRIPT_UNAVAILABLE');
      } finally {
        restore();
      }
    });

    it('playback / seek 同步 throw → NETWORK_ERROR 路径', async () => {
      // READ_ACTIVE_VIDEO_PLAYBACK + SEEK_ACTIVE_VIDEO 都不走 C_S_U 同步 throw 路径
      // —— sendMessageWithRecovery 返回 NETWORK_ERROR；readPlaybackState 返回 null，
      // seekVideo 返回 createErrorResponse(NETWORK_ERROR)。
      const { bridge, restore } = setupChromeThrow('lost tab');
      try {
        expect(await bridge.readPlaybackState(1)).toBeNull();
        const seekResult = await bridge.seekVideo(1, {
          type: 'SEEK_ACTIVE_VIDEO',
          payload: { seconds: 60 },
        });
        expect(seekResult.ok).toBe(false);
        if (!seekResult.ok) expect(seekResult.error.code).toBe('NETWORK_ERROR');
      } finally {
        restore();
      }
    });

    it('injectContentScript 失败 → logWarn 收到注入失败日志（生产工厂语义）', async () => {
      const originalChrome = (globalThis as { chrome?: unknown }).chrome;
      const logWarn = vi.fn();
      const fakeChrome = {
        tabs: {
          sendMessage: (_t: number, _m: unknown, cb: (r: unknown) => void) => {
            fakeChrome.runtime.lastError = { message: 'Receiving end does not exist' };
            cb(undefined);
            fakeChrome.runtime.lastError = null;
          },
        },
        runtime: { lastError: null as { message: string } | null },
        scripting: {
          executeScript: (_o: unknown, cb: () => void) => {
            fakeChrome.runtime.lastError = { message: 'cannot access' };
            cb();
            fakeChrome.runtime.lastError = null;
          },
        },
      };
      (globalThis as unknown as { chrome: typeof fakeChrome }).chrome = fakeChrome;
      const bridge = createChromeContentScriptBridge({
        createErrorResponse: (c: string, m: string) => ({ ok: false, error: { code: c, message: m } }),
        logWarn,
      });
      try {
        const result = await bridge.fetchYouTubeTranscript(1, { videoId: 'v' });
        expect(result.ok).toBe(false);
        if (!result.ok) {
          expect(result.error.code).toBe('CONTENT_SCRIPT_UNAVAILABLE');
          expect(result.error.message).toMatch(/主动注入失败/);
        }
        expect(logWarn).toHaveBeenCalled();
        expect(
          logWarn.mock.calls.some((call) =>
            /主动注入 content\.js 失败/.test(String(call[0])),
          ),
        ).toBe(true);
      } finally {
        if (originalChrome === undefined) {
          delete (globalThis as { chrome?: unknown }).chrome;
        } else {
          (globalThis as { chrome: unknown }).chrome = originalChrome;
        }
      }
    });
  });
});
