import { describe, expect, it, vi } from 'vitest';
import { createPlatformReadHandler } from '@extension/background/handlers/platform-read-handler';
import type {
  FetchTranscriptResult,
  PlatformReadHandlerDeps,
  PlatformReadRequest,
} from '@extension/background/handlers/platform-read-handler';
import type { ExtensionRequest, ExtensionResponse } from '@shared/messages';
import type {
  YouTubeTranscriptResult,
  YouTubeTranscriptError,
} from '@shared/youtube-transcript';
import type { BilibiliCookieSnapshot } from '@extension/background/cookie-service';

function makeResult(): YouTubeTranscriptResult {
  return {
    videoId: 'abc123',
    metadata: {
      title: '测试视频',
      author: '测试作者',
      lengthSeconds: 600,
    },
    track: {
      language: 'zh-CN',
      label: '中文（简体）',
      source: 'asr',
      isAutoGenerated: true,
    },
    availableTrackCount: 1,
    cues: [],
    cached: false,
    timings: [],
  };
}

function makeAttempts() {
  return [
    { stage: 'dom_panel', durationMs: 120 },
    { stage: 'parse_dom', durationMs: 80 },
  ];
}

function makeError(): YouTubeTranscriptError {
  return {
    code: 'INNERTUBE_BAD_STATUS',
    message: 'YouTube 转录文本面板不可用',
    status: 500,
    stage: 'dom_panel',
  };
}

function makeCookieSnapshot(): BilibiliCookieSnapshot {
  return {
    header: 'SESSDATA=xxx; bili_jct=yyy',
    loggedIn: true,
    capturedNames: ['SESSDATA', 'DedeUserID', 'bili_jct'],
  };
}

function makeDeps(
  overrides: Partial<PlatformReadHandlerDeps> = {},
): PlatformReadHandlerDeps {
  return {
    getCurrentVideoTabId: vi.fn().mockResolvedValue(7),
    fetchTranscriptFromTab: vi.fn(),
    readBilibiliCookieSnapshot: vi.fn().mockResolvedValue(makeCookieSnapshot()),
    createErrorResponse: vi
      .fn()
      .mockImplementation((code, message): ExtensionResponse => ({
        ok: false,
        error: { code, message },
      })),
    ...overrides,
  };
}

describe('createPlatformReadHandler', () => {
  describe('FETCH_YOUTUBE_TRANSCRIPT', () => {
    it('无当前视频 tab → 返回 NO_ACTIVE_TAB 错误，**不**调用抓取依赖', async () => {
      const fetchTranscriptFromTab = vi.fn();
      const createErrorResponse = vi
        .fn()
        .mockReturnValue({
          ok: false,
          error: { code: 'NO_ACTIVE_TAB', message: '没有找到当前 YouTube 视频标签页' },
        });
      const deps = makeDeps({
        getCurrentVideoTabId: vi.fn().mockResolvedValue(null),
        fetchTranscriptFromTab,
        createErrorResponse,
      });
      const handler = createPlatformReadHandler(deps);
      const request: PlatformReadRequest = {
        type: 'FETCH_YOUTUBE_TRANSCRIPT',
        payload: { videoId: 'abc123' },
      };

      const response = await handler(request);

      expect(createErrorResponse).toHaveBeenCalledWith(
        'NO_ACTIVE_TAB',
        '没有找到当前 YouTube 视频标签页',
      );
      expect(response).toEqual({
        ok: false,
        error: { code: 'NO_ACTIVE_TAB', message: '没有找到当前 YouTube 视频标签页' },
      });
      expect(fetchTranscriptFromTab).not.toHaveBeenCalled();
    });

    it('有 tab → 把 tab ID 和 request.payload 原对象传给字幕依赖', async () => {
      const payload = { videoId: 'abc123', languages: ['zh-CN', 'en'] };
      const transcriptResult: FetchTranscriptResult = {
        ok: true,
        result: makeResult(),
        attempts: makeAttempts(),
      };
      const fetchTranscriptFromTab = vi.fn().mockResolvedValue(transcriptResult);
      const deps = makeDeps({
        getCurrentVideoTabId: vi.fn().mockResolvedValue(42),
        fetchTranscriptFromTab,
      });
      const handler = createPlatformReadHandler(deps);
      const request: PlatformReadRequest = {
        type: 'FETCH_YOUTUBE_TRANSCRIPT',
        payload,
      };

      await handler(request);

      // 引用透传：handler **不**重建 tab ID / payload 参数
      const [calledTabId, calledPayload] = fetchTranscriptFromTab.mock.calls[0]!;
      expect(calledTabId).toBe(42);
      expect(calledPayload).toBe(payload);
    });

    it('字幕成功 → 返回 YOUTUBE_TRANSCRIPT，result / attempts 引用透传', async () => {
      const result = makeResult();
      const attempts = makeAttempts();
      const transcriptResult: FetchTranscriptResult = {
        ok: true,
        result,
        attempts,
      };
      const deps = makeDeps({
        fetchTranscriptFromTab: vi.fn().mockResolvedValue(transcriptResult),
      });
      const handler = createPlatformReadHandler(deps);
      const request: PlatformReadRequest = {
        type: 'FETCH_YOUTUBE_TRANSCRIPT',
        payload: { videoId: 'abc123' },
      };

      const response = await handler(request);

      if (response.ok && response.type === 'YOUTUBE_TRANSCRIPT') {
        // 引用透传：handler **不**重建 result / attempts
        expect(response.payload.result).toBe(result);
        expect(response.payload.attempts).toBe(attempts);
      } else {
        throw new Error('response 不是 YOUTUBE_TRANSCRIPT 成功响应');
      }
    });

    it('字幕失败 → 返回 YOUTUBE_TRANSCRIPT_FAILED，error 引用透传', async () => {
      const error = makeError();
      const transcriptResult: FetchTranscriptResult = {
        ok: false,
        error,
      };
      const deps = makeDeps({
        fetchTranscriptFromTab: vi.fn().mockResolvedValue(transcriptResult),
      });
      const handler = createPlatformReadHandler(deps);
      const request: PlatformReadRequest = {
        type: 'FETCH_YOUTUBE_TRANSCRIPT',
        payload: { videoId: 'abc123' },
      };

      const response = await handler(request);

      if (!response.ok && 'type' in response && response.type === 'YOUTUBE_TRANSCRIPT_FAILED') {
        // error 原对象透传
        expect(response.error).toBe(error);
      } else {
        throw new Error('response 不是 YOUTUBE_TRANSCRIPT_FAILED 错误响应');
      }
    });
  });

  describe('GET_BILIBILI_COOKIES', () => {
    it('调用 cookie snapshot 依赖一次 → 返回 BILIBILI_COOKIES，payload 引用透传', async () => {
      const snapshot = makeCookieSnapshot();
      const readBilibiliCookieSnapshot = vi.fn().mockResolvedValue(snapshot);
      const deps = makeDeps({ readBilibiliCookieSnapshot });
      const handler = createPlatformReadHandler(deps);
      const request: PlatformReadRequest = { type: 'GET_BILIBILI_COOKIES' };

      const response = await handler(request);

      expect(readBilibiliCookieSnapshot).toHaveBeenCalledTimes(1);
      if (response.ok && response.type === 'BILIBILI_COOKIES') {
        // payload 引用透传：handler **不**重建 snapshot
        expect(response.payload).toBe(snapshot);
      } else {
        throw new Error('response 不是 BILIBILI_COOKIES 成功响应');
      }
    });
  });

  it('handler 类型签名：只接受 PlatformReadRequest（编译期验证）', () => {
    // 静态类型断言 —— 不被调用，只为让 type-check 验证类型收窄。
    const _extReq: ExtensionRequest = { type: 'PING' };
    // @ts-expect-error PING 不是 PlatformReadRequest
    const _check: PlatformReadRequest = _extReq;
    void _check;
  });
});
