import { describe, expect, it, vi } from 'vitest';
import {
  createVideoAnalysisService,
  type YouTubePrefetchOutcome,
} from '@extension/background/services/video-analysis-service';
import type { PageContext } from '@shared/page-context';
import type { AnalysisMode } from '@shared/settings';

const youtubeCtxWithVideo = (): PageContext => ({
  platform: 'youtube',
  videoId: 'dQw4w9WgXcQ',
  url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  title: 'never gonna',
  detectedAt: 0,
});

const bilibiliCtx = (): PageContext => ({
  platform: 'bilibili',
  videoId: 'BV1xx',
  url: 'https://www.bilibili.com/video/BV1xx',
  title: 'demo',
  detectedAt: 0,
});

function makeService(
  overrides: Partial<{
    fetchYouTubeTranscript: ReturnType<typeof vi.fn>;
    cookieProvider: ReturnType<typeof vi.fn>;
  }> = {},
) {
  return createVideoAnalysisService({
    fetchYouTubeTranscript: overrides.fetchYouTubeTranscript ?? vi.fn(),
    cookieProvider: overrides.cookieProvider ?? vi.fn().mockResolvedValue(null),
    logWarn: vi.fn(),
  });
}

describe('video-analysis-service.shouldPrefetchYouTubeTranscript', () => {
  it('returns true for youtube + videoId + subtitle', () => {
    const svc = makeService();
    expect(
      svc.shouldPrefetchYouTubeTranscript({
        context: youtubeCtxWithVideo(),
        analysisMode: 'subtitle',
      }),
    ).toBe(true);
  });

  it('returns false for non-youtube platform', () => {
    const svc = makeService();
    expect(
      svc.shouldPrefetchYouTubeTranscript({
        context: bilibiliCtx(),
        analysisMode: 'subtitle',
      }),
    ).toBe(false);
  });

  it('returns false for youtube without videoId', () => {
    const svc = makeService();
    const { videoId: _omit, ...ctx } = youtubeCtxWithVideo();
    expect(
      svc.shouldPrefetchYouTubeTranscript({
        context: ctx,
        analysisMode: 'subtitle',
      }),
    ).toBe(false);
  });
});

describe('video-analysis-service.maybeFetchYouTubeTranscript', () => {
  const baseInput = {
    tabId: 1,
    context: youtubeCtxWithVideo(),
    analysisMode: 'subtitle' as AnalysisMode,
  };

  it('returns skipped for non-youtube platforms', async () => {
    const svc = makeService();
    const result: YouTubePrefetchOutcome = await svc.maybeFetchYouTubeTranscript({
      ...baseInput,
      context: bilibiliCtx(),
    });
    expect(result.kind).toBe('skipped');
  });

  it('returns ok with converted transcript + attempts', async () => {
    const attempts = [{ stage: 'dom_panel', durationMs: 100 }];
    const fetchYouTubeTranscript = vi.fn().mockResolvedValue({
      ok: true,
      result: {
        videoId: 'dQw4w9WgXcQ',
        metadata: { title: 'mock', author: 'mock-author', lengthSeconds: 120 },
        track: {
          language: 'zh-Hans',
          label: 'Chinese (auto-generated)',
          source: 'asr',
          isAutoGenerated: true,
        },
        cues: [],
      },
      attempts,
    });
    const svc = makeService({ fetchYouTubeTranscript });
    const result = await svc.maybeFetchYouTubeTranscript({
      ...baseInput,
      subtitleLanguages: ['en-US', 'zh-CN'],
    });
    expect(result.kind).toBe('ok');
    if (result.kind === 'ok') {
      expect(result.transcript.metadata.platform).toBe('youtube');
      expect(result.transcript.metadata.videoId).toBe('dQw4w9WgXcQ');
      expect(result.transcript.source).toBe('asr');
      expect(result.transcript.language).toBe('zh-Hans');
      expect(result.attempts).toEqual(attempts);
    }
    expect(fetchYouTubeTranscript).toHaveBeenCalledWith(1, {
      videoId: 'dQw4w9WgXcQ',
      languages: ['en-us', 'zh-cn'],
    });
  });

  it('returns business_error for transcript bridge errors', async () => {
    const fetchYouTubeTranscript = vi.fn().mockResolvedValue({
      ok: false,
      error: { code: 'NO_CAPTION_TRACKS', message: 'mock' },
    });
    const svc = makeService({ fetchYouTubeTranscript });
    const result = await svc.maybeFetchYouTubeTranscript(baseInput);
    expect(result.kind).toBe('business_error');
    if (result.kind === 'business_error') {
      expect(result.error.code).toBe('NO_CAPTION_TRACKS');
    }
  });
});

describe('video-analysis-service.maybeFetchYouTubeTranscriptLite', () => {
  const baseInput = {
    tabId: 1,
    context: youtubeCtxWithVideo(),
    analysisMode: 'subtitle' as AnalysisMode,
  };

  it('lite 透传 ok 分支（保留 transcript + attempts）', async () => {
    const fetchYouTubeTranscript = vi.fn().mockResolvedValue({
      ok: true,
      result: {
        videoId: 'dQw4w9WgXcQ',
        metadata: { title: 'mock', author: 'mock-author' },
        track: {
          language: 'en',
          label: 'English',
          source: 'official',
          isAutoGenerated: false,
        },
        cues: [],
      },
      attempts: [{ stage: 'dom_panel', durationMs: 50 }],
    });
    const svc = makeService({ fetchYouTubeTranscript });
    const result = await svc.maybeFetchYouTubeTranscriptLite(baseInput);
    expect(result.kind).toBe('ok');
    if (result.kind === 'ok') {
      expect(result.transcript.metadata.videoId).toBe('dQw4w9WgXcQ');
      expect(result.transcript.source).toBe('official');
      expect(result.transcript.language).toBe('en');
      expect(result.attempts).toEqual([{ stage: 'dom_panel', durationMs: 50 }]);
    }
  });

  it('lite 透传 business_error 分支', async () => {
    const fetchYouTubeTranscript = vi.fn().mockResolvedValue({
      ok: false,
      error: { code: 'CONTENT_SCRIPT_UNAVAILABLE', message: 'mock' },
    });
    const svc = makeService({ fetchYouTubeTranscript });
    const result = await svc.maybeFetchYouTubeTranscriptLite(baseInput);
    expect(result.kind).toBe('business_error');
  });
});

describe('video-analysis-service.fetchMetadataForContext', () => {
  it('YouTube 上下文会查询 cookieProvider', async () => {
    const cookieProvider = vi.fn().mockResolvedValue(null);
    const svc = makeService({ cookieProvider });
    await svc.fetchMetadataForContext(youtubeCtxWithVideo());
    expect(cookieProvider).toHaveBeenCalledWith('youtube');
  });

  it('B 站上下文会查询 cookieProvider', async () => {
    const cookieProvider = vi.fn().mockResolvedValue('SESSDATA=test');
    const svc = makeService({ cookieProvider });
    await svc.fetchMetadataForContext(bilibiliCtx());
    expect(cookieProvider).toHaveBeenCalledWith('bilibili');
  });

  it('未匹配的平台返回 null（不调 cookieProvider）', async () => {
    const cookieProvider = vi.fn();
    const svc = makeService({ cookieProvider });
    const result = await svc.fetchMetadataForContext({
      platform: 'unknown',
      url: 'https://example.com/foo',
      title: 'mock',
      detectedAt: 0,
    });
    expect(result).toBeNull();
    expect(cookieProvider).not.toHaveBeenCalled();
  });
});
