import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import {
  clearYouTubeTranscriptCache,
  fetchYouTubeTranscriptInPageContext,
  getCurrentYouTubeVideoId,
} from '@extension/content/youtube-transcript-fetcher';

function setPage(html: string): void {
  document.body.innerHTML = html;
}

function appendTranscriptSegments(): void {
  const panel = document.createElement('div');
  panel.innerHTML = `
    <ytd-transcript-segment-renderer>
      <div class="segment-timestamp">0:00</div>
      <yt-formatted-string class="segment-text">You are going to give up.</yt-formatted-string>
    </ytd-transcript-segment-renderer>
    <ytd-transcript-segment-renderer>
      <div class="segment-timestamp">0:09</div>
      <yt-formatted-string class="segment-text">That is okay.</yt-formatted-string>
    </ytd-transcript-segment-renderer>
  `;
  document.body.append(panel);
}

function setCaptionTracksPage(
  tracks: ReadonlyArray<{
    readonly baseUrl: string;
    readonly languageCode: string;
    readonly kind?: string;
    readonly name?: { readonly simpleText?: string; readonly runs?: Array<{ readonly text: string }> };
  }>,
): void {
  setPage(`
    <script>
      window.ytInitialPlayerResponse = ${JSON.stringify({
        captions: {
          playerCaptionsTracklistRenderer: {
            captionTracks: tracks,
          },
        },
      })};
    </script>
  `);
}

function textResponse(text: string, status = 200): Response {
  return new Response(text, { status });
}

const TIMEDTEXT_XML =
  '<transcript>' +
  '<text start="0" dur="2">Official caption</text>' +
  '<text start="2" dur="3">Second caption</text>' +
  '</transcript>';

const JSON3_CAPTION = JSON.stringify({
  events: [
    { tStartMs: 0, dDurationMs: 1200, segs: [{ utf8: 'JSON3 caption' }] },
    { tStartMs: 1200, dDurationMs: 800, segs: [{ utf8: 'fallback works' }] },
  ],
});

describe('YouTube transcript fetcher', () => {
  beforeEach(() => {
    clearYouTubeTranscriptCache();
    document.title = 'Never Gonna Give You Up - YouTube';
    setPage('');
  });

  afterEach(() => {
    document.body.innerHTML = '';
    clearYouTubeTranscriptCache();
  });

  describe('getCurrentYouTubeVideoId', () => {
    it('extracts id from watch URL', () => {
      expect(getCurrentYouTubeVideoId('https://www.youtube.com/watch?v=dQw4w9WgXcQ')).toBe(
        'dQw4w9WgXcQ',
      );
    });

    it('extracts id from youtu.be URL', () => {
      expect(getCurrentYouTubeVideoId('https://youtu.be/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
    });

    it('extracts id from /shorts/ URL', () => {
      expect(getCurrentYouTubeVideoId('https://www.youtube.com/shorts/dQw4w9WgXcQ')).toBe(
        'dQw4w9WgXcQ',
      );
    });

    it('extracts id from /embed/ URL', () => {
      expect(getCurrentYouTubeVideoId('https://www.youtube.com/embed/dQw4w9WgXcQ')).toBe(
        'dQw4w9WgXcQ',
      );
    });

    it('falls back to the active YouTube player video id when SPA URL has no watch id', () => {
      const player = document.createElement('div') as unknown as HTMLElement & {
        getVideoData: () => { readonly video_id: string };
      };
      player.id = 'movie_player';
      player.getVideoData = () => ({ video_id: 'htk4B9rIMaA' });
      document.body.append(player);

      expect(getCurrentYouTubeVideoId('https://www.youtube.com/')).toBe('htk4B9rIMaA');
    });

    it('returns null for non-YouTube URLs', () => {
      expect(getCurrentYouTubeVideoId('https://www.bilibili.com/video/BV1xx411c7mD/')).toBeNull();
    });
  });

  describe('fetchYouTubeTranscriptInPageContext', () => {
    it('rejects invalid videoId', async () => {
      await expect(
        fetchYouTubeTranscriptInPageContext({ videoId: 'invalid' }),
      ).rejects.toMatchObject({ code: 'NO_VIDEO_ID', stage: 'extract_video_id' });
    });

    it('reads cues from page captionTracks before trying transcript panel DOM', async () => {
      document.title = "(10) I'm 100% playing this - YouTube";
      setCaptionTracksPage([
        {
          baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en',
          languageCode: 'en',
          name: { simpleText: 'English' },
        },
      ]);
      const fetchMock = vi.fn(async (_input: RequestInfo | URL) => textResponse(TIMEDTEXT_XML));

      const result = await fetchYouTubeTranscriptInPageContext(
        { videoId: 'dQw4w9WgXcQ' },
        { fetchImpl: fetchMock },
      );

      expect(fetchMock).toHaveBeenCalledTimes(1);
      expect(result.track).toMatchObject({
        language: 'en',
        label: 'English',
        source: 'official',
        isAutoGenerated: false,
      });
      expect(result.cues).toEqual([
        { start: 0, end: 2, text: 'Official caption' },
        { start: 2, end: 5, text: 'Second caption' },
      ]);
      expect(result.metadata.title).toBe("I'm 100% playing this");
      expect(result.timings.map((timing) => timing.stage)).toEqual([
        'caption_tracks',
        'caption_fetch',
        'parse_caption',
      ]);
    });

    it('uses current player captionTracks passed from background before stale page HTML', async () => {
      setCaptionTracksPage([
        {
          baseUrl: 'https://www.youtube.com/api/timedtext?v=OLD_VIDEO_1&lang=en',
          languageCode: 'en',
          name: { simpleText: 'Old English' },
        },
      ]);
      const fetchMock = vi.fn(async (_input: RequestInfo | URL) => textResponse(TIMEDTEXT_XML));

      const result = await fetchYouTubeTranscriptInPageContext(
        {
          videoId: 'dQw4w9WgXcQ',
          pageCaptionTracks: [
            {
              baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en',
              languageCode: 'en',
              name: { simpleText: 'English' },
            },
          ],
        },
        { fetchImpl: fetchMock },
      );

      expect(fetchMock).toHaveBeenCalledTimes(1);
      const firstFetchArg = fetchMock.mock.calls[0]?.[0];
      expect(firstFetchArg?.toString()).toContain('v=dQw4w9WgXcQ');
      expect(result.track.label).toBe('English');
      expect(result.cues[0]?.text).toBe('Official caption');
    });

    it('falls back to fmt=json3 when the original caption URL returns an empty body', async () => {
      setCaptionTracksPage([
        {
          baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en&kind=asr',
          languageCode: 'en',
          kind: 'asr',
          name: { runs: [{ text: 'English (auto-generated)' }] },
        },
      ]);
      const fetchMock = vi.fn(async (input: RequestInfo | URL) => {
        const url = input.toString();
        return url.includes('fmt=json3') ? textResponse(JSON3_CAPTION) : textResponse('');
      });

      const result = await fetchYouTubeTranscriptInPageContext(
        { videoId: 'dQw4w9WgXcQ' },
        { fetchImpl: fetchMock },
      );

      expect(fetchMock).toHaveBeenCalledTimes(2);
      expect(result.track.source).toBe('asr');
      expect(result.cues).toEqual([
        { start: 0, end: 1.2, text: 'JSON3 caption' },
        { start: 1.2, end: 2, text: 'fallback works' },
      ]);
    });

    it('ignores stale captionTracks that belong to a previous YouTube SPA video', async () => {
      setCaptionTracksPage([
        {
          baseUrl: 'https://www.youtube.com/api/timedtext?v=OLD_VIDEO_1&lang=en',
          languageCode: 'en',
          name: { simpleText: 'English' },
        },
      ]);
      appendTranscriptSegments();
      const fetchMock = vi.fn(async () => textResponse(TIMEDTEXT_XML));

      const result = await fetchYouTubeTranscriptInPageContext(
        { videoId: 'dQw4w9WgXcQ' },
        { fetchImpl: fetchMock },
      );

      expect(fetchMock).not.toHaveBeenCalled();
      expect(result.track.label).toBe('YouTube 转录文本');
      expect(result.cues[0]?.text).toBe('You are going to give up.');
    });

    it('reads cues from an already opened YouTube transcript panel', async () => {
      setPage(`
        <h1><yt-formatted-string>How to fix your entire life in 1 day</yt-formatted-string></h1>
        <ytd-video-owner-renderer>
          <div id="channel-name"><a>Dan Koe</a></div>
        </ytd-video-owner-renderer>
        <video></video>
        <ytd-transcript-segment-renderer>
          <div class="segment-timestamp">0:00</div>
          <yt-formatted-string class="segment-text">You are going to give up.</yt-formatted-string>
        </ytd-transcript-segment-renderer>
        <ytd-transcript-segment-renderer>
          <div class="segment-timestamp">0:09</div>
          <yt-formatted-string class="segment-text">That is okay.</yt-formatted-string>
        </ytd-transcript-segment-renderer>
      `);

      const result = await fetchYouTubeTranscriptInPageContext({
        videoId: 'dQw4w9WgXcQ',
      });

      expect(result.videoId).toBe('dQw4w9WgXcQ');
      expect(result.cached).toBe(false);
      expect(result.metadata.title).toBe('How to fix your entire life in 1 day');
      expect(result.metadata.author).toBe('Dan Koe');
      expect(result.track.label).toBe('YouTube 转录文本');
      expect(result.track.language).toBe('unknown');
      expect(result.availableTrackCount).toBe(1);
      expect(result.cues).toEqual([
        { start: 0, end: 9, text: 'You are going to give up.' },
        { start: 9, text: 'That is okay.' },
      ]);
      expect(result.timings.map((timing) => timing.stage)).toEqual([
        'caption_tracks',
        'dom_panel',
        'parse_dom',
      ]);
    });

    it('clicks Show transcript and waits for rendered segments', async () => {
      setPage('<button id="show-transcript">Show transcript</button>');
      document.querySelector('#show-transcript')?.addEventListener('click', () => {
        window.setTimeout(appendTranscriptSegments, 10);
      });

      const result = await fetchYouTubeTranscriptInPageContext(
        { videoId: 'dQw4w9WgXcQ' },
        { transcriptOpenTimeoutMs: 500 },
      );

      expect(result.cues).toHaveLength(2);
      expect(result.cues[0]?.text).toBe('You are going to give up.');
      expect(result.timings.map((timing) => timing.stage)).toContain('dom_panel');
    });

    it('supports Chinese YouTube transcript entry "转写文稿"', async () => {
      setPage('<button id="transcript-button" aria-label="转写文稿">转写文稿</button>');
      document.querySelector('#transcript-button')?.addEventListener('click', appendTranscriptSegments);

      const result = await fetchYouTubeTranscriptInPageContext(
        { videoId: 'dQw4w9WgXcQ' },
        { transcriptOpenTimeoutMs: 500 },
      );

      expect(result.cues.map((cue) => cue.text)).toEqual([
        'You are going to give up.',
        'That is okay.',
      ]);
    });

    it('does not treat "关闭转写文稿" as an open transcript trigger', async () => {
      let closeClicked = false;
      setPage(`
        <button id="close-transcript" aria-label="关闭转写文稿"></button>
        <button id="open-transcript" aria-label="转写文稿">转写文稿</button>
      `);
      document.querySelector('#close-transcript')?.addEventListener('click', () => {
        closeClicked = true;
      });
      document.querySelector('#open-transcript')?.addEventListener('click', appendTranscriptSegments);

      const result = await fetchYouTubeTranscriptInPageContext(
        { videoId: 'dQw4w9WgXcQ' },
        { transcriptOpenTimeoutMs: 500 },
      );

      expect(closeClicked).toBe(false);
      expect(result.cues).toHaveLength(2);
    });

    it('expands description before clicking transcript entry', async () => {
      setPage('<button id="expand">Show more</button>');
      document.querySelector('#expand')?.addEventListener('click', () => {
        const transcriptButton = document.createElement('button');
        transcriptButton.textContent = 'Show transcript';
        transcriptButton.addEventListener('click', appendTranscriptSegments);
        document.body.append(transcriptButton);
      });

      const result = await fetchYouTubeTranscriptInPageContext(
        { videoId: 'dQw4w9WgXcQ' },
        { transcriptOpenTimeoutMs: 500 },
      );

      expect(result.cues.map((cue) => cue.start)).toEqual([0, 9]);
    });

    it('parses timestamp and text from fallback segment text', async () => {
      setPage(`
        <ytd-transcript-segment-renderer>1:02 A segment with fallback text</ytd-transcript-segment-renderer>
        <ytd-transcript-segment-renderer>1:05 Another segment</ytd-transcript-segment-renderer>
      `);

      const result = await fetchYouTubeTranscriptInPageContext({
        videoId: 'dQw4w9WgXcQ',
      });

      expect(result.cues).toEqual([
        { start: 62, end: 65, text: 'A segment with fallback text' },
        { start: 65, text: 'Another segment' },
      ]);
    });

    it('caches result for 5 minutes and returns cached=true on second call', async () => {
      setPage(`
        <ytd-transcript-segment-renderer>
          <div class="segment-timestamp">0:00</div>
          <yt-formatted-string class="segment-text">First transcript.</yt-formatted-string>
        </ytd-transcript-segment-renderer>
      `);

      const first = await fetchYouTubeTranscriptInPageContext({ videoId: 'dQw4w9WgXcQ' });
      document.body.innerHTML = '';
      const second = await fetchYouTubeTranscriptInPageContext({ videoId: 'dQw4w9WgXcQ' });

      expect(first.cached).toBe(false);
      expect(second.cached).toBe(true);
      expect(second.cues).toEqual(first.cues);
      expect(second.timings).toEqual([{ stage: 'cache', durationMs: 0 }]);
    });

    it('throws NO_CAPTION_TRACKS when no transcript panel or trigger exists', async () => {
      setPage('<main>No transcript here.</main>');

      await expect(
        fetchYouTubeTranscriptInPageContext(
          { videoId: 'dQw4w9WgXcQ' },
          { transcriptOpenTimeoutMs: 20 },
        ),
      ).rejects.toMatchObject({
        code: 'NO_CAPTION_TRACKS',
        stage: 'dom_panel',
      });
    });
  });
});
